name: OHRI CI

on:
  push:
    tags:
      - "*"
    branches:
      - "*"

  pull_request:
    branches:
      - "*"
    types: [opened, synchronize]
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run build
        run: yarn build

  docs_deployment:
    runs-on: ubuntu-latest

    needs: build

    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      # Update the Microfrontends to reflect what we have in the Working branch
      - uses: garygrossgarten/github-action-ssh@release
        name: Run the Update Next Site Script
        with:
          command: cd /usr/share/tomcat/microfrontends/ohri_docs && sh update_docs.sh
          host: ${{ secrets.HISTAC_HOST }}
          username: ${{ secrets.HISTAC_USERNAME }}
          privateKey: ${{ secrets.HISTAC_KEY}}
          port: ${{ secrets.HISTAC_PORT }}
